config/routes.rb
PartyPlanner::Application.routes.draw do
  get "home/index"

  root :to => "home#index"

  resources :ingredients

  resources :recipes

  resources :sections

  resources :cookbooks

end

app/models/cookbook.rb
class Cookbook < ActiveRecord::Base
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  # GET /cookbooks
  # GET /cookbooks.json
  def index
    @cookbooks = Cookbook.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cookbooks }
    end
  end

  # GET /cookbooks/1
  # GET /cookbooks/1.json
  def show
    @cookbook = Cookbook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cookbook }
    end
  end

  # GET /cookbooks/new
  # GET /cookbooks/new.json
  def new
    @cookbook = Cookbook.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cookbook }
    end
  end

  # GET /cookbooks/1/edit
  def edit
    @cookbook = Cookbook.find(params[:id])
  end

  # POST /cookbooks
  # POST /cookbooks.json
  def create
    @cookbook = Cookbook.new(params[:cookbook])

    respond_to do |format|
      if @cookbook.save
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully created.' }
        format.json { render json: @cookbook, status: :created, location: @cookbook }
      else
        format.html { render action: "new" }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cookbooks/1
  # PUT /cookbooks/1.json
  def update
    @cookbook = Cookbook.find(params[:id])

    respond_to do |format|
      if @cookbook.update_attributes(params[:cookbook])
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookbooks/1
  # DELETE /cookbooks/1.json
  def destroy
    @cookbook = Cookbook.find(params[:id])
    @cookbook.destroy

    respond_to do |format|
      format.html { redirect_to cookbooks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/views/cookbooks/_form.html.erb
<%= form_for(@cookbook) do |f| %>
  <% if @cookbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cookbook.errors.count, "error") %> prohibited this cookbook from being saved:</h2>

      <ul>
      <% @cookbook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :coverart %><br />
    <%= f.text_field :coverart %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cookbooks/edit.html.erb
<h1>Editing cookbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @cookbook %> |
<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/index.html.erb
<h1>Listing cookbooks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Subtitle</th>
    <th>Author</th>
    <th>Coverart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cookbooks.each do |cookbook| %>
  <tr>
    <td><%= cookbook.title %></td>
    <td><%= cookbook.subtitle %></td>
    <td><%= cookbook.author %></td>
    <td><%= cookbook.coverart %></td>
    <td><%= link_to 'Show', cookbook %></td>
    <td><%= link_to 'Edit', edit_cookbook_path(cookbook) %></td>
    <td><%= link_to 'Destroy', cookbook, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cookbook', new_cookbook_path %>

app/views/cookbooks/new.html.erb
<h1>New cookbook</h1>

<%= render 'form' %>

<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @cookbook.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @cookbook.subtitle %>
</p>

<p>
  <b>Author:</b>
  <%= @cookbook.author %>
</p>

<p>
  <b>Coverart:</b>
  <%= @cookbook.coverart %>
</p>


<%= link_to 'Edit', edit_cookbook_path(@cookbook) %> |
<%= link_to 'Back', cookbooks_path %>